-- Properties Seed Data
INSERT INTO properties (
  id, title, slug, city, area, description, nightly_price, cleaning_fee, max_guests, amenities, images, featured_image, rules, active, featured
) VALUES
(
  'e632cb6a-1234-4567-8901-abcdef123456', 
  'The Chamber', 
  'the-chamber', 
  'Secret Location', 
  '', 
  'An intense, sensual sanctuary bathed in deep red ambient light. The Chamber by Nothingness is designed for absolute intimacy and exploration. Featuring raw, dark walls, heavy chains, a St. Andrew''s cross, and premium restraints, this space offers a cinematic, underground experience far removed from the ordinary world. The heavy ornate rugs and tungsten accents contrast with the intense fetish elements, creating an atmosphere of mysterious luxury.', 
  1500, 
  150, 
  2, 
  '["St. Andrew''s Cross", "Premium Restraints", "Ambient Red Lighting", "Soundproofing", "Heavy Chains", "Custom Dark Furniture"]', 
  '{"/images/the-chamber.jpg"}', 
  '/images/the-chamber.jpg', 
  'Absolute Discretion Required\nNo photography outside the space\nRespect the equipment', 
  true, 
  true
),
(
  'c432cb6a-1234-4567-8901-abcdef123457', 
  'The Concrete Villa', 
  'concrete-villa', 
  'NY', 
  'Hidden Woods', 
  'A brutalist masterpiece hidden deep within a secluded forest. The Concrete Villa contrasts harsh, angular architecture with the soft, chaotic beauty of nature. Large glass windows blur the line between inside and out. It is a space designed for total isolation and deep reflection.', 
  1200, 
  100, 
  4, 
  '["Private Forest", "Fire Pit", "Minimalist Kitchen", "Tungsten Lighting", "Sound System"]', 
  '{"/images/property-1.png"}', 
  '/images/property-1.png', 
  'No parties\nNo pets\nQuiet hours after 10PM', 
  true, 
  false
),
(
  'b432cb6a-1234-4567-8901-abcdef123458', 
  'Underground Art Loft', 
  'underground-loft', 
  'Berlin', 
  'Germany', 
  'An industrial space reimagined as an intimate sanctuary for creators. Featuring exposed concrete, muted gold accents, and a curated collection of contemporary art. It feels like an exclusive gallery where you are allowed to sleep.', 
  850, 
  80, 
  2, 
  '["Art Studio Space", "Vinyl Player", "Espresso Machine", "Blackout Curtains", "Curated Library"]', 
  '{"/images/property-2.png"}', 
  '/images/property-2.png', 
  'No smoking\nRespect the artwork', 
  true, 
  false
),
(
  'a432cb6a-1234-4567-8901-abcdef123459', 
  'The Glass House', 
  'glass-house', 
  'Kyoto', 
  'Japan', 
  'A transparent pavilion floating above a zen garden. Designed for those who have nothing to hide. It offers an immersive experience of the changing seasons.', 
  1500, 
  150, 
  2, 
  '["Zen Garden", "Tea Room", "Heated Floors", "Soaking Tub"]', 
  '{"/images/hero.png"}', 
  '/images/hero.png', 
  'Remove shoes indoors\nNo loud music', 
  true, 
  true
) ON CONFLICT (slug) DO UPDATE SET 
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  nightly_price = EXCLUDED.nightly_price,
  amenities = EXCLUDED.amenities,
  images = EXCLUDED.images,
  featured_image = EXCLUDED.featured_image,
  rules = EXCLUDED.rules;
